### ISSUE TITLE
Add tags to this repo

### ISSUE THREAD

**Issue by ghost** [ShFsn/tu154b#15]
This issue is not about aircraft. Add tags to this repo to show more users :)

**Comment by ShFsn** [comment]
Ok, I'll try to make them "non-senceless" (as  far as I can explain it on english).

**Comment by ShFsn** [comment]
And btw, you can write in "global" "chat" issue on english if you want to -- it's normal.

**Comment by ghost** [comment]
I mean add topics to this repo like this:
https://github.com/Octal450/MD-11
flightgear, simulation...

**Comment by ShFsn** [comment]
Oh, understood. Didn't thought about them.

**Comment by ShFsn** [comment]
Btw, they named topics as I can see:
![image](https://user-images.githubusercontent.com/52665144/167686604-eae6ea90-913c-4da1-afb8-65e4412e3eb1.png)

**Comment by ShFsn** [comment]
I've added some. Do you have any other suggestions?

**Comment by ghost** [comment]
No and please mention me because notifications are not working xD

**Comment by ghost** [comment]
I think I fixed notifications problem.
