### ISSUE TITLE
Visual model: Frosting glass

### ISSUE THREAD

**Issue by ShFsn** [ShFsn/tu154b#2]
Strange behavior of `Glass` shader was detected: cockpit glass can frost / fog up, despite the fact that this behavior is not written for the shader.

**Comment by ghost** [comment]
Affects at least Intel video on Linux.

Possible scenarios.
- Texture PNG having alpha=1 and trans=1 of AC3D material is somehow being ignored.
- Effects/Glass conflicting something (perhaps another effect has been applied to the glass objects, iirc one should never apply more than one effect)

Commenting out the part that applies Effects/Glass makes the issue go away.

**Comment by ghost** [comment]
Информация по Effects/Glass:

> Glass по умолчанию реагирует только на дождь, да и то там нужно свой вектор скорости прописывать. И что характерно, в wiki пример расчёта этого вектора какой-то убогий.
> 
> Вот более правильный расчёт, хотя он тоже не идеален:
> 
> https://gitlab.com/mdanil/Tu-144D/-/blob/master/PRules/animations.xml#L898
> 
> Опционально ему можно скормить признак работы очистителей, уровень затуманивания и уровень обледенения, например так:
> 
> https://gitlab.com/mdanil/Tu-144D/-/blob/master/PRules/animations.xml#L1002
> 
> Но для правильной работы очистителей нужно обозначить площадь, которую они протирают:
> 
> https://wiki.flightgear.org/ALS_technical_notes#Functional_masks
> 
> Через ту же вещь можно задать зоны, которые не обледеневают.

**Comment by ShFsn** [comment]
Maybe I can run FG on integrated Intel graphics to check.

Ну, да, можно и на русском. :)

**Comment by ShFsn** [comment]
Запустил на встроенной графике интел, оверлей земли от такого покоробило:
![image](https://user-images.githubusercontent.com/52665144/141682393-64d8ac20-3e66-43cb-9fcb-2dfb85c38899.png)

Но стекло осталось в порядке.

**Comment by ShFsn** [comment]
Похоже, что проблема решена. Дело в том, что ФГ на линуксе регистрозависим и ему обязательно нужен был `Effects/glass`, а на шиндовсе и `Effects/Glass` работал без нареканий.

Problem solved, patch applied.
